# Generated by Django 5.1.2 on 2024-11-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_client_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type_client',
        ),
    ]
